name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres_db:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      keycloak:
        image: bitnami/keycloak:latest
        volumes:
          - realm-export.json:/tmp/realm-export.json
        env:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          KC_DB: postgres
          KC_DB_USERNAME: postgres
          KC_DB_PASSWORD: postgres
          KC_DB_URL: jdbc:postgresql://localhost:5432/postgres
          JAVA_OPTS_APPEND: "-Dkeycloak.profile.feature.upload_scripts=enabled"
          KEYCLOAK_IMPORT: /tmp/realm-export.json
        ports:
          - 8080:8080
    steps:
#      - name: Check conn 1
#        run: ls -la /home/runner/work/NewsPublicIntegrationTests/NewsPublicIntegrationTests/src/main/resources/static/images
      - name: Check conn 2
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          ls -la /usr/bin
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify