name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres_db:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          # will assign a random free host port
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      keycloak:
        image: jboss/keycloak:8.0.1
        command:
          - " -b 0.0.0.0"
        volumes:
          - "./keycloak/realm-export.json:/opt/jboss/keycloak/bin/keycloak_export_dir/realm-export.json"
        environment:
          KEYCLOAK_USER: admin
          KEYCLOAK_PASSWORD: admin
          KEYCLOAK_IMPORT: /opt/jboss/keycloak/bin/keycloak_export_dir/realm-export.json
        ports:
          - "8080:8080"
    steps:
#      - name: Download Maven
#        run: |
#          curl -sL https://www-eu.apache.org/dist/maven/maven-3/3.9.1/binaries/apache-maven-3.9.1-bin.zip -o maven.zip
#          apt-get -y install unzip
#          unzip -d /usr/share maven.zip
#          rm maven.zip
#          ln -s /usr/share/apache-maven-3.9.1/bin/mvn /usr/bin/mvn
#          echo "M2_HOME=/usr/share/apache-maven-3.9.1" | tee -a /etc/environment
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify